### ISSUE TITLE
KeyError in remove_stale_columns

### ISSUE THREAD

**Issue by joestringer** [cilium/microscope#35]
I was running a `--force-command` command, and was using tmux paste mode (`^B [`) and hit this:

```
Traceback (most recent call last):                                     
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                 
    self.run()                                                         
  File "/usr/local/lib/python3.6/threading.py", line 864, in run       
    self._target(*self._args, **self._kwargs)                          
  File "/bin/microscope/microscope/ui/ui.py", line 114, in wait_for_values                                                                    
    monitor_columns, empty_column_timeout)                             
  File "/bin/microscope/microscope/ui/ui.py", line 35, in remove_stale_columns                                                                
    del columns[k]                                                     
KeyError: 'cilium-whpxv'
```

**Comment by nebril** [comment]
Fixed by cec2384992f00596510c5e72d7356045242b0e30
