### ISSUE TITLE
KeyError 'orchestration-identity'

### ISSUE THREAD

**Issue by nebril** [cilium/microscope#47]
This happens in k8s 1.10 cluster created by cilium gingko test suite
```
Traceback (most recent call last):                                                        
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main              
    "__main__", mod_spec)                                                                 
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code                         
    exec(code, run_globals)                                                               
  File "/bin/microscope/__main__.py", line 124, in <module>                               
  File "/bin/microscope/__main__.py", line 114, in main                                   
  File "/bin/microscope/microscope/monitor/monitor.py", line 159, in run                  
  File "/bin/microscope/microscope/monitor/monitor.py", line 175, in get_monitor_command  
  File "/bin/microscope/microscope/monitor/monitor.py", line 251, in retrieve_endpoint_ids
  File "/bin/microscope/microscope/monitor/monitor.py", line 257, in <setcomp>            
KeyError: 'orchestration-identity'                                                        
```

**Comment by raybejjani** [comment]
This is likely now `.status.labels.security-relevant`
