### ISSUE TITLE
The user system:serviceaccount:kube-system:microscope cannot list ciliumendpoints.cilium.io at the cluster scope error

### ISSUE THREAD

**Issue by chilcano** [cilium/microscope#62]
Hi there,
I've deployed Microscope in Minikube, the pod is running successfully but can not execute any microscope filter.

```bash
$ kubectl apply -f https://raw.githubusercontent.com/cilium/microscope/master/docs/microscope.yaml
$ kubectl exec -it microscope -n kube-system -- sh
...
/usr/src/microscope # microscope --from-selector piggyback=ok

closing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/bin/microscope/__main__.py", line 137, in <module>
  File "/bin/microscope/__main__.py", line 123, in main
  File "/bin/microscope/microscope/monitor/monitor.py", line 324, in run
  File "/bin/microscope/microscope/monitor/monitor.py", line 343, in get_monitor_command
  File "/bin/microscope/microscope/monitor/monitor.py", line 410, in retrieve_endpoint_data
  File "/bin/microscope/kubernetes/client/apis/custom_objects_api.py", line 823, in list_cluster_custom_object
  File "/bin/microscope/kubernetes/client/apis/custom_objects_api.py", line 923, in list_cluster_custom_object_with_http_info
  File "/bin/microscope/kubernetes/client/api_client.py", line 321, in call_api
  File "/bin/microscope/kubernetes/client/api_client.py", line 155, in __call_api
  File "/bin/microscope/kubernetes/client/api_client.py", line 342, in request
  File "/bin/microscope/kubernetes/client/rest.py", line 231, in GET
  File "/bin/microscope/kubernetes/client/rest.py", line 222, in request
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 26 Apr 2018 17:36:27 GMT', 'Content-Length': '323'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ciliumendpoints.cilium.io is forbidden: User \"system:serviceaccount:kube-system:microscope\" cannot list ciliumendpoints.cilium.io at the cluster scope","reason":"Forbidden","details":{"group":"cilium.io","kind":"ciliumendpoints"},"code":403}
```

I've review the `docs/microscope.yaml` and can see the `system:serviceaccount:kube-system:microscope` defined properly.

I'm using:
* minikube version: v0.25.0
* kubernetes version: 1.8
* RBAC enabled
* kubectl version: 1.9.2
* mac osx: 10.13.4

Any idea?.
Thanks.

**Comment by chilcano** [comment]
That worked!
Regards.
